[project]
name = "android-hand-door"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium-robotics>=1.4.1",
    "gymnasium[other,robotics]>=1.2.0",
    "stable-baselines3[extra]>=2.7.0",
]
